### PR TITLE
DAT-54078

### PR DESCRIPTION
**Pull request by makc-dataloop**
@fadiDL take 2

### CODE REVIEW

**Review by fadiDL — APPROVED** [review]

**Review by fadiDL — CHANGES_REQUESTED** [review]
@makc-dataloop Please add the `searchQuery` and `lastSearchQuery` to the return value.
Also please add a test, it should be pretty easy to test that the lastSearchQuery is set correctly 
and  that calling the function with no change does not emit the `update:modelValue`

**Comment by makc-dataloop** [comment]
@fadiDL 
> Please add the searchQuery and lastSearchQuery to the return value.

do you mean like moving the check to onEnterKey() ?

**Comment by fadiDL** [comment]
> @fadiDL
> 
> > Please add the searchQuery and lastSearchQuery to the return value.
> 
> do you mean like moving the check to onEnterKey() ?

No not at all, in the vue3 setup function you can do return { ... } in order to expose the values 
you need to expose the two values in order for you to use it from tests and other places

**Comment by makc-dataloop** [comment]
@fadiDL for the test, do I modify [this one](https://github.com/dataloop-ai/components/blob/main/tests/DlSmartSearch/DlSmartSearchInput.spec.ts#L399-L428)?

**Review by fadiDL — APPROVED** [review]

**Pull request merged**
