### PR TITLE
Update splitByQuotes.ts

### PR DESCRIPTION
**Pull request by jigneshdavara314**
#585 Fix for search

**Thank you for your contribution to the repo. Before submitting this PR, please make sure:**
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests
- [ ] You have updated documentation
- [ ] You have tested your changes

**Please provide a description of the changes proposed in the pull request and reference any related issues in the repository.**

**Please indicate if this PR contains:**
- [ ] A bug fix
- [ ] A feature request
- [ ] Breaking changes
- [ ] An enhancement

### CODE REVIEW

**Comment by fadiDL** [comment]
@jigneshdavara314 looks clean to me but can you please add unit tests to check all edge cases please?

**Comment by jigneshdavara314** [comment]
> @jigneshdavara314 looks clean to me but can you please add unit tests to check all edge cases please?

@fadiDL  I have updated pull request with testcases

**Comment by fadiDL** [comment]
Thanks for the test to showcase that the new split by quote works @jigneshdavara314 
Unfortunately, I have cloned your repo and tested the fix myself before moving forward and doing a full review with the tests and it does not solve the main issue of the ticket. 

Your optimization may be an upgrade and a better version of the current splitByQuote but after looking depeer into this it does not seem to be the root of the problem. 

I simply tested it with a query of 

test = 'A(B)C' 

and after blur the smartsearch would change the text to 

test = 'ABC' 
meaning special characters between single quotation marks is not solved. 

Closing this PR as it does not relate to the proper solution. can revisit it in the future if the optimization is really worth it at the moment.

**Comment by jigneshdavara314** [comment]
@fadiDL In the same PR  there was also a fix for 590 and 591  please check and let me know you comment on this too

**Pull request closed without merging**
