### PR TITLE
DlKpi component development

### PR DESCRIPTION
**Pull request by vadim-popa-opentech**
---------------------------------------------
| Q  | A |
| ------------- | ------------- |
| Related tickets | https://opentechdev.atlassian.net/browse/DLCL-731 |
| Vue2 |  Y |
| Vue3 |  Y |
| Storybook 7 |  Y |
| Tests |  Y |
| Demo |  Y |

### Changelog

* New: The KPI component has been created

------------------------

### CODE REVIEW

**Review by SorinOpt — DISMISSED** [review]

**Comment by fadiDL** [comment]
@vadim-popa-opentech great work, this component should replace the simple texts inside the dl-counters component as a dl-kpi is a single dl-counter

please update the PR

**Comment by Yonatan-Mesika** [comment]
@fadiDL @vadim-popa-opentech FYI - I'll connect this new component to the DlCounters.

**Comment by fadiDL** [comment]
- KPI should have bordered prop as its not always required.
- KPI Object and Counters object are different 
- Maybe initialize defaults
- No need for auto width
- Keep in UL/LI form and just use kpi component instead

**Comment by fadiDL** [comment]
@vadim-popa-opentech can you please pick it up again ?

The desired behavior is a KPI 
is a single entity not an array. 

it should have borderd property with default false so to not have the box border

Once those changes are done 
Dlcounters needs to be updated and for it to be a list of dlkpis 

instead of ul li and items.


NOTE ! 
please make sure the circular dependency check is not a thing. i couldnt get the app to work for me because of circular dependencies. 
lets pick it up together soon and set up a register order or code load order for us 

we need it as we are having issues with components using other components. we will restructure the files together

**Review by fadiDL — DISMISSED** [review]

**Review by fadiDL — APPROVED** [review]

**Pull request merged**
