### PR TITLE
fixed activeQuery error

### PR DESCRIPTION
**Pull request by prodan-eric**
Fixed console error upon pressing search.  It follows to build the String->JSON parser

### CODE REVIEW

**Comment by fadiDL** [comment]
@prodan-eric please add to this pr the translation of emitting search with a json that includes `{ query: <search-query>}`

**Review by fadiDL — CHANGES_REQUESTED** [review]
@prodan-eric please add to this pr the translation of emitting search with a json that includes { query: <search-query>}

**Comment by fadiDL** [comment]
@prodan-eric The base of this repo has caused issues since its from development and we have not yet released that release. can you rebase with the relevant comments to a new PR ?

**Comment by prodan-eric** [comment]
@fadiDL 

New PR https://github.com/dataloop-ai/components/pull/136

**Pull request closed without merging**
