### PR TITLE
fixes #590

### LINKED ISSUE #590: [BUG] DlSmartSearch - when using arrow keys to navigate suggestion and clicking enter it doesnt reset the caret position

### PR DESCRIPTION
**Pull request by makc-dataloop**
@fadiDL this should cover #592 as well - you can left/right, type or apply suggestions at the position. ~~I will add some tests here later today~~ - they were added.

there is a corner case arising form the design issue: we dont know if suggestion is a value or an operator and, as a result, when applying it mid-string the code does not know if it should keep or replace following expression - for example, if user backspaced the value and then picked the one from suggestions the code will replace the following expression which is an operator and not a value.

**edit**: ~~actually there is another issue with suggestions popping up mid-value, I need to add the fix for that~~ - done.

### CODE REVIEW

**Comment by fadiDL** [comment]
@makc-dataloop tried to do the simple 

Test1 = 'test'

And place cursor at the start and after i wrote Test2 = 'test2'
it gave suggestion of AND and OR which is great
Once i selected AND it overwrote on the Test1 operator resulting in 

Test2 = 'test2' AND = 'test'

**Comment by makc-dataloop** [comment]
@fadiDL I assume you mean this situation:
Screen Shot 2023-10-30 at 6 18 10 PM
with the caret before Test1, in which case yes it does replace Test1 with AND because it does not know if Test1 is the key, the value or the operator, it is just non-whitespace token.

Actually I feel like I should have asked what they want to - if they want to keep the text on the right or to replace. Replace made more sense to me, e g when you want to replace one value with another. Otherwise you would end up with `Test = value3 value2 value1` after selecting from the value list.

**Comment by fadiDL** [comment]
I dont think we want to remove the next phrase anytime only as you said if we are handling values
But thats different than what i demonstarted can you please make sure i t doesnt delete parts of the query when we add AND and OR operators ?

**Comment by makc-dataloop** [comment]
@fadiDL yes I could do that, if you are okay with getting results like Test1 = test1 AND OR Test2 = test2

**Comment by makc-dataloop** [comment]
@fadiDL I added the changes you have requested

**Comment by makc-dataloop** [comment]
@fadiDL updated again

**Pull request merged**
