### PR TITLE
DAT-71796: fix applying suggestions after strings

### PR DESCRIPTION
**Pull request by makc-dataloop**

### CODE REVIEW

**Comment by makc-dataloop** [comment]
unrelated DlAlert test failed 😔
Screenshot 2024-06-04 at 3 42 48 PM

**Comment by fadiDL** [comment]
> unrelated DlAlert test failed 😔 Screenshot 2024-06-04 at 3 42 48 PM

Fixed, missed .only was commited. will have to handle it in the future

**Comment by fadiDL** [comment]
@makc-dataloop Why not base this check on the value type of the field ? is that possible ? then we can perform based on the value of the field instead of how the suggestion was provided which can be more correct

**Comment by makc-dataloop** [comment]
@fadiDL in this case the `replace` regex is too simple and replaces too much of a string, so the check (new `if` condition) is narrowing it down - so not really related to the type of the field. this is a temporary fix any way, since it would stop working once DAT-71446 is implemented.

**Comment by fadiDL** [comment]
> @fadiDL in this case the `replace` regex is too simple and replaces too much of a string, so the check (new `if` condition) is narrowing it down - so not really related to the type of the field. this is a temporary fix any way, since it would stop working once DAT-71446 is implemented.
> 
> I was thinking to add way more tests like the one in this PR, and then we would have some freedom to change the code more aggressively?

No problem, lets merge this for now. ticket DAT-71446 would require the type checking i was referencing. Alsoooo more tests is alwaaayys welcome 😁

**Review by fadiDL — APPROVED** [review]

**Pull request merged**
