### PR TITLE
DlTabs -> add top-right slot

### PR DESCRIPTION
**Pull request by SorinOpt**
**Thank you for your contribution to the repo. Before submitting this PR, please make sure:**
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests
- [ ] You have updated documentation
- [ ] You have tested your changes

**Please provide a description of the changes proposed in the pull request and reference any related issues in the repository.**

**Please indicate if this PR contains:**
- [ ] A bug fix
- [ ] A feature request
- [ ] Breaking changes
- [x] An enhancement

image

UPDATE: 
Screenshot 2023-04-25 at 16 53 48

### CODE REVIEW

**Review by advaa1234 — DISMISSED** [review]

**Comment by fadiDL** [comment]
image

@SorinOpt please take care of the edgecase as given example. i pushed the demo to showcase

**Review by fadiDL — CHANGES_REQUESTED** [review]
fix the relevant edge case

**Comment by SorinOpt** [comment]
@fadiDL what behavior should have this edge case?

**Comment by fadiDL** [comment]
@SorinOpt the behavior here should be that the icon is at the end of the tabs and not behind the buttons 

think of the dl-tabs now as a container for tabs 

Div that holds all of them with overflow shows icons at its edges 
and a slot on the side for extra  buttons

**Comment by fadiDL** [comment]
@Barp311 please review the new updated screenshot 

example here 
image

Give insight on the new design and if you want to also have the horizontal line and verticcal ones or what to do here.

**Comment by Barp311** [comment]
we need all the options :1. horizontal line and vertical lines. - evrething need to be customized.
The vertical line should be customized: 1. Only on the tabs. 2. The length of the page and under the buttons. 

Screenshot 2023-04-27 at 15 59 50

[figma](https://www.figma.com/file/UTx83SSFrIOohMzG9e2rAj/dataloop-design-system?type=design&node-id=1934-8860&t=6cPZV2KONHs3jLJs-0)

**Comment by fadiDL** [comment]
@SorinOpt please also note that vertical tabs does not highlight the dl-separator there

**Comment by SorinOpt** [comment]
> @SorinOpt please check this design issue
> 
> image
> 
> in our demo currently the separator is also colored image

if the last tab, there is no separator to indicate which tab is active.  It is ok ?

**Comment by SorinOpt** [comment]
> @SorinOpt please check this design issue
> 
> image
> 
> in our demo currently the separator is also colored image

@fadiDL fixed

**Comment by fadiDL** [comment]
rebased to main

**Review by fadiDL — APPROVED** [review]

**Pull request merged**
