### PR TITLE
fix/DLCL-906-dl-date-time-range-opacity

### PR DESCRIPTION
**Pull request by vadim-popa-opentech**
---------------------------------------------
| Q  | A |
| ------------- | ------------- |
| Related tickets | https://opentechdev.atlassian.net/browse/DLCL-906 |
| Vue2 |  Y |
| Vue3 |  Y |
| Storybook |  N |
| Tests |  Y |
| Demo |  N |

### Changelog

* Fix: The background color of start/end selected date has changed to #8FA0FF

------------------------

### CODE REVIEW

**Comment by fadiDL** [comment]
@vadim-popa-opentech please provide screenshots here so that @Barp311 can confirm the new design as she requested in the ticket

**Comment by vadim-popa-opentech** [comment]
> @vadim-popa-opentech please provide screenshots here so that @Barp311 can confirm the new design as she requested in the ticket

image

image

**Comment by Barp311** [comment]
@vadim-popa-opentech 
light mode looks good. 
for the dark mode please use this color: #535E96

**Comment by vadim-popa-opentech** [comment]
> @vadim-popa-opentech light mode looks good. for the dark mode please use this color: #535E96

image

**Review by fadiDL — APPROVED** [review]

**Pull request merged**
